class DatabaseQueries {
  // User Profile Queries
  static const String getUserProfile = "SELECT * FROM profiles WHERE id = @id";
  static const String updateUserProfile = "UPDATE profiles SET name = @name, email = @email, phone_number = @phone_number WHERE id = @id";

  // Blog Queries
  static const String getAllBlogs = "SELECT content, poster_name FROM blogs ORDER BY created_at DESC";
  static const String insertBlog = "INSERT INTO blogs (content, poster_name) VALUES (@content, @poster_name)";

  // Schedule/Appointments Queries
  static const String getAppointments = "SELECT * FROM appointments WHERE user_id = @user_id ORDER BY start_time ASC";
  static const String insertAppointment = "INSERT INTO appointments (title, description, start_time, end_time, user_id) VALUES (@title, @description, @start_time, @end_time, @user_id)";
  static const String deleteAppointment = "DELETE FROM appointments WHERE id = @id";

  /* 
  SQL Table Schemas for Reference:

  CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    name TEXT,
    email TEXT,
    phone_number TEXT
  );

  CREATE TABLE blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    poster_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  */
}
